import discord
from discord.ext.commands import Bot
from discord.ext import commands
from discord import member
from discord.ext.commands import has_permissions, MissingPermissions
from discord.ext.commands import bot
from discord.utils import get
import asyncio
import inspect
import functools
import typing


def check_if_it_is_me(ctx):
    return ctx.message.author.id == 277100410500677632

class owner:
    def __init__(self, bot):
        self.bot = bot

    @commands.command(pass_context = True)
    @commands.check(check_if_it_is_me)
    async def okick(self, ctx, user: discord.Member):
        """If you see this command that means someone is getting fucked by the owner. btw "o" in the command stands for owner"""
        await ctx.guild.kick(user)
		
    @commands.command(pass_context=True)
    @commands.check(check_if_it_is_me)
    async def oban(self, ctx, member: discord.Member):
        """If you see this command that means someone is getting fucked by the owner. btw "o" in this command stands for owner"""
        await ctx.guild.ban(member)
	
# @okick.error
# async def okick_error(ctx, error):
	# if isinstance(error, CheckFailure):
	    # await ctx.send("You don't have the required permissions. Loser..")
		
    @commands.command(pass_context=True)
    @commands.check(check_if_it_is_me)
    async def omega_mass_ping(self, ctx, member: discord.Member):
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))
        await ctx.send("<@{}>".format(member.id))




    @commands.command(pass_context=True)
    @commands.check(check_if_it_is_me)
    async def change(self, ctx, lol):
        game = discord.Game(lol)
        await self.bot.change_presence(activity=game)




def setup(bot):
    bot.add_cog(owner(bot))